Updated windows window/frontend to fix issue with html select positioning
wailsapp/wails pull request #1082
Opened 2022-01-16 15:24 UTC by MikeSchaap

Fixes #1081

Need to wait for the following PR (https://github.com/leaanthony/go-webview2/pull/5) to merge so `go-webview2` exposes the `NotifyParentWindowPositionChanged()` method.

Was not sure how to correctly expose the chromium object to the window object. Do you agree with the proposed fix? Doesn't feel really solid imo

2022-01-17 19:08 UTC, leaanthony commented
I would suggest having the notify function in the Window struct rather than options, as that's user options. In frontend Run, you can set the notify callback directly on the window struct after setting up chromium

2022-01-17 21:02 UTC, MikeSchaap commented
I moved the `notifyParentWindowPositionChanged` method to the Window struct and set the value in the `Run` method of `Frontend`. I was getting a nil pointer on the `WndProc` because it was called before the `notifyParentWindowPositionChanged` method was set. I moved the `winc.RegMsgHandler(w)` method call from the `NewWindow` method to the `Window.Run` method to make sure `notifyParentWindowPositionChanged` method was set before it was being used. Do you have any idea if this might interfere with anything else? From my (short) testing, everything seemed to still work.

2022-01-17 21:05 UTC, MikeSchaap commented
Also, I guess we still have to wait for a new tag on the `go-webview2` repo before we can update the version in `go.mod` right?

2022-01-22 22:41 UTC, leaanthony requested changes
I think this is almost ready to go 👍

2022-01-22 22:41 UTC, leaanthony commented on v2/internal/frontend/desktop/windows/window.go
> +	winc.RegMsgHandler(w)
Could we put this back to where it was and deal with the nil pointer scenario?

2022-01-22 22:41 UTC, leaanthony commented on v2/internal/frontend/desktop/windows/window.go
> +		w.notifyParentWindowPositionChanged()
```suggestion
		if w.notifyParentWindowPositionChanged != nil {
			w.notifyParentWindowPositionChanged()
		}
```

2022-01-22 22:41 UTC, leaanthony commented
Also need to resolve conflicts

2022-01-23 14:54 UTC, MikeSchaap commented
Oh no, i'm pretty sure i messed up... I shouldn't work on sunday i guess.. Trying to figure out how to 'restore' this PR

2022-01-23 15:30 UTC, MikeSchaap commented
Looks like I managed to revert the messup. Also moved the `winc.RegMsgHandler(result)` back to it's original position and resolved the conflicts. I believe we should be good to go now

2022-01-24 10:06 UTC, leaanthony commented
> Also, I guess we still have to wait for a new tag on the `go-webview2` repo before we can update the version in `go.mod` right?

Nah, just update the dependency to use latest commit. I usually specify this like `go get .....@ab2c3b2`

2022-01-26 07:41 UTC, stffabi commented
> > Also, I guess we still have to wait for a new tag on the `go-webview2` repo before we can update the version in `go.mod` right?
> 
> Nah, just update the dependency to use latest commit. I usually specify this like `go get .....@ab2c3b2` Do you need to update go.mod + go.sum in this PR?

PR #1105 already bumped the `go-webview2` dependency and that PR has been merged. Therefore we could merge this PR without needing to bump it. 
Should we squash the commits before merging?

2022-01-26 07:48 UTC, leaanthony commented
LGTM!

2022-01-26 07:48 UTC, merged

2022-01-26 07:57 UTC, MikeSchaap commented
Cheers 🍾

2022-01-26 08:45 UTC, leaanthony commented
Congrats on your first PR!