docs: add macos custom menu EditMenu tips
wailsapp/wails pull request #1423
Opened 2022-05-24 00:13 UTC by daodao97

On macos platform, if custom the menu, we should append EditMenu to enable Cmd+C,Cmd+V,Cmd+Z... shortcut

2022-05-24 19:14 UTC, stffabi requested changes
Thank you so much @daodao97 for this docs improvement.

I only have one minor comment to be resolved, which seems to be a copy paste error.

2022-05-24 19:14 UTC, stffabi commented on website/docs/reference/menus.mdx
> +	m.Append(menu.EditMenu())  // on macos platform, we should append EditMenu to enable Cmd+C,Cmd+V,Cmd+Z... shortcut
Shouldn't this be `AppMenu.Append(`?

2022-05-24 23:05 UTC, daodao97 commented on website/docs/reference/menus.mdx
> +	m.Append(menu.EditMenu())  // on macos platform, we should append EditMenu to enable Cmd+C,Cmd+V,Cmd+Z... shortcut
fixed.

2022-05-25 06:47 UTC, stffabi approved these changes

2022-05-25 06:49 UTC, merged

2022-05-25 06:49 UTC, stffabi commented
Thanks again @daodao97 for taking your time improving the docs.