feature - add race detector to build & dev
wailsapp/wails pull request #1426
Opened 2022-05-26 19:04 UTC by Lyimmi

This pull request resolves wailsapp/wails#1425 feature request, by adding the `-race` flag to `wails build` and `wails dev` commands.

2022-05-27 03:25 UTC, leaanthony approved these changes

2022-05-27 03:28 UTC, leaanthony requested changes
Thanks for doing this! Would it be possible to add the flag to the docs in the website docs here? 

https://github.com/wailsapp/wails/blob/master/website/docs/reference/cli.mdx

2022-05-27 05:17 UTC, Lyimmi commented
Pushed in the changes for the docs.

2022-05-28 05:06 UTC, leaanthony approved these changes
Nice work!

2022-05-28 05:07 UTC, merged