Added EmailIt and Modal File Manager
wailsapp/wails pull request #1725
Opened 2022-08-10 08:33 UTC by raguay

I think I added the two properly. Let me know if I need to change anything. Thanks.

2022-08-10 09:26 UTC, leaanthony commented
Thanks for this 🙏 Did you intend to add the images too?

2022-08-11 02:48 UTC, raguay commented
I believe I added the images to the correct place. If they need to be
different or moved around, please let me know.

On Wed, Aug 10, 2022 at 4:26 PM Lea Anthony ***@***.***>
wrote:

> Thanks for this 🙏 Did you intend to add the images too?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wailsapp/wails/pull/1725#issuecomment-1210405314>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAS7JR5VM3FQ4U2I6QP22TDVYNYT3ANCNFSM56DTSMWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-11 08:08 UTC, leaanthony requested changes
I'd love to merge this but the lack of images will create broken pages. If you push the images to your branch this PR should pick them up 🙏

2022-08-11 08:08 UTC, leaanthony commented on website/docs/community/showcase/emailit.mdx
> +   <img src="/img/showcase/emailit.png"></img><br/>
This Image does not exist in the repo or this PR

2022-08-11 08:21 UTC, closed without merging