Add print functionality to v2
wailsapp/wails pull request #2822
Opened 2023-08-15 00:35 UTC by aangelisc

This is a backport of the print functionality that was created for v3 in [this commit](https://github.com/wailsapp/wails/commit/cdf397aaa9c7026e2c121d9d1b4212f3a86b405c).

A couple notes before this is approved for merging:

- Have only tested this on MacOS not Windows or Linux.
- I think it's definitely prudent to add the configuration to the print function and leave sensible defaults if the developer/user provides no config.
- I've removed the margins that were added in the v3 version. I think it's more sensible to have no default margin but open to suggestions.

Objective-C is not a language I'm familiar with so I'm not 100% on this despite the fact that I've basically just copy-pasted most of this with some minor edits 😊

2023-08-24 11:14 UTC, leaanthony requested changes
Looks great. Can you please add an update to the changelog in the website/static dir.

2023-08-27 22:52 UTC, leaanthony commented
@aangelisc - Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

2023-08-28 22:41 UTC, aangelisc commented
@leaanthony CHANGELOG updated! 😊 Sorry it took so long

2023-09-04 22:33 UTC, aangelisc commented
Hey @leaanthony, this should be ready to merge now 😊

2023-09-05 07:53 UTC, leaanthony commented
Thanks @aangelisc - I think we also need to update the runtime documentation too 😅

2023-09-05 20:34 UTC, aangelisc commented
@leaanthony updated the runtime docs too!

2023-09-05 21:55 UTC, leaanthony approved these changes
Looking good! Thanks for your work on this 🙏

2023-09-05 21:55 UTC, merged