Devtools hotkey
wailsapp/wails pull request #2915
Opened 2023-09-16 08:44 UTC by leaanthony

# Description

This PR adds an F12 hotkey shortcut to open the devtools window, whenever the app is built with the `devtools` flag.
Not sure if this could be an issue for signed apps... I don't think it is...

Fixes #2908 

## Type of change
  
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
  
Create a new project, build with `wails build` and check F12 does nothing. Build with `wails build -devtools` and press F12.

- [x] Windows
- [x] macOS
- [x] Linux
  
# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-09-16 11:18 UTC, mmghv commented
Works as expected on windows.

Now that F12 opens the devtools, maybe `-devtools` shouldn't enable the default contextmenu? so only `EnableDefaultContextMenu` option enables it in production.

2023-09-16 12:03 UTC, leaanthony commented
I'm open to discussion on this. The only edge case is Mac apps that want it enabled and want it on the appstore (does that combo even make sense???).

2023-09-16 12:18 UTC, mmghv commented
Can't speak for Mac devs, but if I understand correctly there's no way around it if you want F12 or a runtime method to open it.

Honestly F12 makes a lot of sense and makes life easier, it also solves the default contextmenu problem because now you don't have to show it with `-devtools`.

2023-09-17 08:15 UTC, stffabi approved these changes
LGTM, should we also warn in build.go that private APIs are being used on macOS when build-tag `devtools` is used?

https://github.com/wailsapp/wails/blob/3116c1a62240f4b3441c697e945fd0355c3f2bb4/v2/pkg/commands/build/build.go#L351-L353

2023-09-18 10:40 UTC, leaanthony commented
I've changed the key combination to `CTRL/CMD+SHIFT+F12` to make it less likely to clash with current bindings.

2023-09-18 10:48 UTC, leaanthony commented
@mmghv - I've removed what I think is the right code to stop `devtools` enabling the default context menu. It looks like it was only enabled in Windows?

2023-09-18 11:11 UTC, mmghv commented
> I've removed what I think is the right code to stop devtools enabling the default context menu. It looks like it was only enabled in Windows?

No it exists in all platforms but each with it's own way, also what you changed disabled the default context-menu on windows in `debug` & `dev`, revert it and I'll do it along with some relevant docs changes in a separate PR after you merge this.

2023-09-18 12:14 UTC, mmghv requested changes

2023-09-18 12:14 UTC, mmghv commented on v2/internal/frontend/desktop/windows/frontend.go
> +	err = settings.PutAreDefaultContextMenusEnabled(f.frontendOptions.EnableDefaultContextMenu)
This change disables the default context-menu on windows in dev & debug because  `f.devtools` is enabled for `-devtools`, `-debug` and dev mode.

2023-09-18 12:25 UTC, leaanthony commented
Will do tomorrow 👍

2023-09-18 19:55 UTC, leaanthony commented
@mmghv - change reverted 👍

2023-09-18 19:56 UTC, merged