[v2 mac] add fullscreen option to preference
wailsapp/wails pull request #2953
Opened 2023-09-29 10:09 UTC by fkhadra

# Description

This PR adds the option to enable/disable fullscreen support on Mac. For example, when this option is enabled, it allows the user to display a video in fullscreen mode.

Fixes # 2099

## Type of change
  
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?
  
I've created a new wails app that point to my changes. The app only render a video. When the user hover the video a fullscreen button is displayed allowing the user to switch in fullscreen mode.

https://github.com/wailsapp/wails/assets/5574267/eb338fe3-437f-4f9f-9155-14d12145a7ba

Repository: https://github.com/fkhadra/wails-fix-2099

- [ ] Windows
- [x] macOS
- [ ] Linux
  
## Test Configuration

```sh
# Wails
Version | v2.6.0

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 13.5.2   |
| ID           | 22G91    |
| Go Version   | go1.21.0 |
| Platform     | darwin   |
| Architecture | arm64    |
└─────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version   |
| Xcode command line tools  | N/A          | Installed | 2397      |
| Nodejs                    | N/A          | Installed | 18.17.0   |
| npm                       | N/A          | Installed | 9.6.7     |
| *Xcode                    | N/A          | Available |           |
| *upx                      | N/A          | Installed | upx 4.1.0 |
| *nsis                     | N/A          | Available |           |
└──────────────────── * - Optional Dependency ─────────────────────┘

# Diagnosis
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-09-30 11:01 UTC, leaanthony approved these changes

2023-10-01 17:02 UTC, mikeee requested changes
Gofmt should clean these up for you

2023-10-01 17:13 UTC, fkhadra commented
Actually, the indention on the IDE was ok but I was using space instead of tab, thanks for pointing out.

![Screenshot 2023-10-01 at 19 08 50](https://github.com/wailsapp/wails/assets/5574267/e7e3c552-14e8-4211-b5c4-54d010055acb)

2023-10-01 20:05 UTC, leaanthony approved these changes

2023-10-01 20:05 UTC, merged

2023-10-01 20:05 UTC, leaanthony commented
Thanks @fkhadra 🙏

2023-10-01 20:12 UTC, fkhadra commented
Your welcome !