Add support for interface generation and enums
wailsapp/wails pull request #3047
Opened 2023-11-10 13:31 UTC by APshenkin

# Description

Some engineers prefer interfaces rather than classes for typescript types. So I added option in `wails.json` to choose between `classes` and `interfaces`. Classes are chosen as default for backward compatibility.

Also typescriptify supports providing types for enums. https://github.com/tkrajina/typescriptify-golang-structs#enums
As generation for them are sligtly different, I added `EnumBind` to App configuration like this

```
err := wails.Run(&options.App{
		Title:  "wails-app",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		Bind: []interface{}{
			app,
		},
		EnumBind: []interface{}{
			AllWeekdays,
		},
	})
```

This then generate proper enums in `model.ts` file, so types are not missing if you return something in structs

## Type of change
  
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [x] Windows
- [x] macOS
- [x] Linux
  
## Test Configuration
I created some showcase here https://github.com/APshenkin/wails-open-file/tree/feature/ts-interfaces-enums

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-11-10 13:32 UTC, APshenkin commented
@leaanthony curios about your input for that 😊

2023-11-11 03:06 UTC, leaanthony approved these changes
Thanks for this! Just a small question 👍

2023-11-11 03:06 UTC, leaanthony commented on v2/internal/binding/binding.go
> +		println(enum.Kind())
Is this still needed?

2023-11-11 03:11 UTC, leaanthony requested changes
Actually, we should have both enum + interface tests in `binding/binding_test` to make sure we're tracking this going forward.

2023-11-11 10:24 UTC, APshenkin commented on v2/internal/binding/binding.go
> +		println(enum.Kind())
removed

2023-11-11 10:25 UTC, APshenkin commented
@leaanthony will write the tests for this on weekends

2023-11-12 12:20 UTC, APshenkin commented
@leaanthony added some tests
```
GeneratedJsEntityWithIntEnumTest,
GeneratedJsEntityWithStringEnumTest,
GeneratedJsEntityWithEnumTsName,
GeneratedJsEntityWithNestedStructInterfacesTest,
ImportedEnumTest,
```

As well as fixed the case, when struct contains imported enum (before it doesn't track type for it correctly)

2023-11-14 11:21 UTC, leaanthony commented
No, just need time to review 🙏

2023-11-22 16:35 UTC, APshenkin commented
@leaanthony @stffabi 
Just kind reminder on that 🙂

I want to use enums in my project as it will be much convenient to follow contracts between frontend and backend then 🙂

I currently use `replace` in go.mod but this adds additional overhead for CI/CD and other devs to install everything properly 🥲

2023-11-25 19:46 UTC, leaanthony approved these changes

2023-11-25 19:50 UTC, leaanthony commented
Thanks @APshenkin 🙏

2023-11-25 19:50 UTC, merged