Generated project helper package.json.
wailsapp/wails pull request #952
Opened 2021-11-20 11:49 UTC by Snider

As NPM is a Wails dependancy adding a simple package.json to a generated derivative project will help colaberators on those projects.

Some of these people will be designers and web devs with zero GoLang experience.

I have added a postinstall hook so that `npm install` at a derivative projects root will install Wails & any dependancies found in fontend/package.json

This means a prerequesite for derivative projects is simly "Install GoLang, NodeJS and `run npm install`"

2021-11-20 20:29 UTC, leaanthony commented
Thanks for raising this. How is the postinstall hook triggered?

2021-11-20 20:32 UTC, Snider commented
it's run every time `npm install` is run as a post-process hook.

2021-11-23 11:11 UTC, leaanthony requested changes

2021-11-23 11:11 UTC, leaanthony commented on v2/cmd/wails/internal/commands/generate/template/base/package.json
> +    "setup": "go install github.com/wailsapp/wails/v2/cmd/wails@v2.0.0-beta.20"
Could we change this to `@latest`?

2021-11-23 11:18 UTC, Snider commented
ugg, yes. i was not on master when i pressed that, darn.

2021-11-23 11:18 UTC, closed without merging